chore: improve gh actions

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,12 +1,30 @@
 name: Publish to npm
-
 on:
   push:
-    branches:
-      - main  
-
+    paths:
+      - 'package.json'
 jobs:
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 22
+      - name: check version
+        id: check
+        uses: EndBug/version-check@v2
+      - name: Log when changed
+        if: steps.check.outputs.changed == 'true'
+        run: |
+          echo "Error: ${{ steps.check.outputs.version }} is not new. Now exiting."
+          exit 1
+      - name: Install dependencies
+        run: npm ci
+      - name: Run tests
+        run: npm test
   publish:
+    needs: test
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -15,7 +33,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
-          node-version: 20
+          node-version: 22
           registry-url: 'https://registry.npmjs.org'
       - name: Install dependencies
         run: npm ci
